### ISSUE TITLE
URL Copy Error 

### ISSUE THREAD

**Issue by samanthablankers** [DataSeer/dataseer-web#272] opened 2021-04-19 22:24 UTC
Hello, 

We are having some issues in copying the public URL for a given article pdf. This error message appears and the URL is not effectively copied to the clipboard. 

![Screen Shot 2021-04-19 at 6 22 31 PM](https://user-images.githubusercontent.com/72994526/115310769-6afce380-a13c-11eb-86d8-31ec0a19ddaa.png)
![Screen Shot 2021-04-19 at 6 22 38 PM](https://user-images.githubusercontent.com/72994526/115310775-6c2e1080-a13c-11eb-8ee8-03166f5445a2.png)

Thank you!
Samantha

**Comment by samanthablankers** [comment] 2021-04-24 22:35
Okay I use chrome and I cleared the cache/refreshed but I still have the same error, strange. @timvines19 also had this problem, is it still not working for you Tim?

**Comment by NicolasKieffer** [comment] 2021-05-12 09:02
I will work on this issue today.

**Comment by NicolasKieffer** [comment] 2021-05-12 14:40
Should be fixed now (unfortunately I cannot reproduce this bug on my side)

**Comment by timvines19** [comment] 2021-05-15 18:35
this issue is now fixed

**Closed by timvines19** 2021-05-15 18:35 UTC
